services:
  mysql:
    image: mysql:latest
    container_name: mysql_ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: password4demo
      MYSQL_DATABASE: test_ecommercedb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  node:
    image: node:latest
    container_name: node_ecommerce
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  db_data: